### PR TITLE
feat: merge teams into pull requests

### LINKED ISSUE #73: feat: merge teams into pull requests

### PR DESCRIPTION
**Pull request by mikededo**
The merge is not direct, since a pull request knows its team by first
accessing the repository: `PullRequest => Repository => Team`.

Closes #73

### CODE REVIEW

**Review by plozanol — APPROVED** [review]

**Review by manerow — APPROVED** [review]

**Review by sdomingobasora — APPROVED** [review]

**Comment by manerow** [comment]
I've just realized we were setting the references in the opposite way on the UserOptionController: setting the pullRequestList to the repository entity, the userList and the repositoryList to the Team entity and the teamList to the Organization Entity.
Looking at the FK of our database we should change the rest to: Set to each team its organization, set each user and repository its team and, like you did on the PR, set each pull request its repository.

**Comment by mikededo** [comment]
We can keep both approaches, I don't mind. In this case this approach was easier.

**Comment by plozanol** [comment]
Why all add/remove methods I wrote on entities are removed? This approach was made on purpose to use bidirectional OneToMany which is the optimal way, and rely on the ManyToOne side to propagate all entity state changes.

The add/remove methods allow synchronizing both relation sides setting the associations at once and avoiding inconsistencies hard to track.

You can check more detail in this post:
https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/

**Comment by mikededo** [comment]
Yes, I saw the implementation of the previous methods, but the reason why I did not mind @manero deleting them is because I would prefer keeping classes simple. This means keeping only methods that are being used. Java is already bloated enough so I would prefer reducing the amount of methods and similar that we have, basically removing them all if not used.  
Plus, I needed in the future their implementation is simple enough.

**Comment by plozanol** [comment]
Understood, that seems a good reason then. Also didn't like so much unused boilerplate code, just keep in mind that we will need the code when the controller recovers the information from github api and before we send the bloated entities to the persistence layer.

**Comment by mikededo** [comment]
I'm fixing the association in #92

**Pull request merged**
