### PR TITLE
feat: add `SaveAllRepositories` use case

### LINKED ISSUE #76: SaveRepository

### PR DESCRIPTION
**Pull request by sdomingobasora**
Equivalent to #83 

Closes #76

### CODE REVIEW

**Comment by mikededo** [comment]
I haven't mentioned this in other PRs, but, could the `saveAll` method fail? If yes, what should we do about it?

**Comment by sdomingobasora** [comment]
> I haven't mentioned this in other PRs, but, could the `saveAll` method fail? If yes, what should we do about it?

After a bit of research, there are some cases where `saveAll` could fail:
- If the entity ID (in this case, `repository.id`) was null
- If JPA detected foreign key violations
- If connection with the database host was lost
- ...?

So it's a valid concern and we might want to handle some of these errors.

However, repetitively handling exceptions in every use case would mean some code duplication, e.g. when we're checking for the database connection. Would it be unreasonable to abstract some of this away, extend the functionality of database use cases with a [decorator](https://refactoring.guru/design-patterns/decorator), or use this chance to create the chain of responsibility to performs checks before something is saved?

I would like to hear the others' opinion on this. Maybe I'm overcomplicating things.

**Comment by mikededo** [comment]
> However, repetitively handling exceptions in every use case would mean some code duplication, e.g. when we're checking for the database connection. Would it be unreasonable to abstract some of this away, extend the functionality of database use cases with a decorator, or use this chance to create the chain of responsibility to performs checks before something is saved?

Seems a bit too much for the MVP, we should focus on it post-mvp (IMO).

**Comment by mikededo** [comment]
We are keeping track of the error control issue in #97! Closing and rebasing this pr! 🚢

**Pull request merged**
